import {Inter} from "next/font/google"
import "./globals.css"
import Header from "./component/Header"
import UserContextProvider from "./lib/UserContext"

const inter = Inter({subsets: ["latin"]})

export const metadata = {
  title: "Airbnb",
  description: "Generated by create next app",
}

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserContextProvider>
          <Header />
          <div className="mt-24">{children}</div>
        </UserContextProvider>
      </body>
    </html>
  )
}
